=== Sayali4535/SayaliDeshpande_VehicleIdentifier/vehicle-identifier-test-57ad6ed6d95b/config/vehicle-identifier-config.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
      targetNamespace="http://com/vehicle/identifier/config"
      xmlns:tns="http://com/vehicle/identifier/config"
      elementFormDefault="qualified" version="1.0">

      <annotation>
            <documentation>
            This file defines vehicle identification input.
            </documentation>
      </annotation>

      <element name="vehicles">
            <complexType>
                  <sequence>
                        <element ref="tns:vehicle" minOccurs="0" maxOccurs="unbounded" />
                  </sequence>
            </complexType>
      </element>

      <element name="vehicle">
            <complexType>
                  <sequence>
                        <element name="id" type="string" maxOccurs="1"/>
                        <element name="frame" type="tns:frame" maxOccurs="1"/>
                        <sequence>
                  <element name="wheels" type="tns:wheels" maxOccurs="1" />
            </sequence>
                        <element name="powertrain" type="string" maxOccurs="1"/>
                  </sequence>
            </complexType>
      </element>

      <complexType name="frame">
            <sequence>
                  <element name="material" type="string" maxOccurs="1"></element>
            </sequence>
      </complexType>

      <complexType name="wheels">
            <sequence>
                  <element name="wheel" type="tns:wheel" minOccurs="0" maxOccurs="4"></element>
            </sequence>
      </complexType>

      <complexType name="wheel">
            <sequence>
                  <element name="position" type="string" maxOccurs="1"></element>
                  <element name="material" type="string" maxOccurs="1"></element>
            </sequence>
      </complexType>

</schema>

=== Sayali4535/SayaliDeshpande_VehicleIdentifier/vehicle-identifier-test-57ad6ed6d95b/config/vehicle_identifier.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vehicles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://com/vehicle/identifier/config"
	xsi:schemaLocation="http://com/vehicle/identifier/config vehicle-identifier-config.xsd">

	<vehicle>
		<id>vehicle 1</id>
		<frame>
			<material>plastic</material>
		</frame>
		<wheels>
			<wheel>
				<position>left rear</position>
				<material>plastic</material>
			</wheel>
			<wheel>
				<position>right rear</position>
				<material>plastic</material>
			</wheel>
			<wheel>
				<position>front</position>
				<material>plastic</material>
			</wheel>
		</wheels>
		<powertrain>human</powertrain>
	</vehicle>
	<vehicle>
		<id>vehicle 2</id>
		<frame>
			<material>metal</material>
		</frame>
		<wheels>
			<wheel>
				<position>rear</position>
				<material>metal</material>
			</wheel>
			<wheel>
				<position>front</position>
				<material>metal</material>
			</wheel>
		</wheels>
		<powertrain>human</powertrain>
		</vehicle>

<vehicle>
		<id>vehicle 3</id>
		<frame>
			<material>plastic</material>
		</frame>
		<wheels>
</wheels>
		<powertrain>Bernoulli</powertrain>
		</vehicle>

<vehicle>
		<id>vehicle 4</id>
		<frame>
			<material>metal</material>
		</frame>
		<wheels>
			<wheel>
				<position>left rear</position>
				<material>metal</material>
			</wheel>
			<wheel>
				<position>right rear</position>
				<material>metal</material>
			</wheel>
			<wheel>
				<position>right rear</position>
				<material>metal</material>
			</wheel>
			<wheel>
				<position>left rear</position>
				<material>metal</material>
			</wheel>
		</wheels>
		<powertrain>Internal Combustion</powertrain>
		</vehicle>

<vehicle>
		<id>vehicle 5</id>
		<frame>
			<material>metal</material>
		</frame>
		<wheels>
			<wheel>
				<position>rear</position>
				<material>metal</material>
			</wheel>
			<wheel>
				<position>front</position>
				<material>metal</material>
			</wheel>
		</wheels>
		<powertrain>Internal Combustion</powertrain>
		</vehicle>

<vehicle>
		<id>vehicle 6</id>
		<frame>
			<material>metal</material>
		</frame>
		<wheels>
			<wheel>
				<position>rear</position>
				<material>metal</material>
			</wheel>
			<wheel>
				<position>front</position>
				<material>metal</material>
			</wheel>
		</wheels>
		<powertrain>Internal Combustion</powertrain>
		</vehicle>

<vehicle>
		<id>vehicle 7</id>
		<frame>
			<material>metal</material>
		</frame>
		<wheels>
			<wheel>
				<position>rear</position>
				<material>metal</material>
			</wheel>
			<wheel>
				<position>front</position>
				<material>metal</material>
			</wheel>
		</wheels>
		<powertrain></powertrain>
		</vehicle>

</vehicles>
